EvaluationApp.Web/Models/UrlResponseStatModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EvaluationApp.Web.Models
{
    public class UrlResponseStatModel
    {
        public int Id { get; set; }
        [Required]
        [StringLength(300, MinimumLength = 5)]
        public string Url { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        [Required]
        public int ResponseTimeMs { get; set; }

        public int WebsiteUrlId { get; set; }
        public WebsiteUrlModel WebsiteUrl { get; set; }
    }
}

EvaluationApp.Web/Models/WebsiteUrlModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EvaluationApp.Web.Models
{
    public class WebsiteUrlModel
    {
        public int Id { get; set; }
        [Required]
        [StringLength(300, MinimumLength = 5)]
        public string Url { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateCreated { get; set; }
    }
}

EvaluationApp.Web/Controllers/EvaluationController.cs
using AutoMapper;
using EvaluationApp.BL.ModelsBL;
using EvaluationApp.BL.Services;
using EvaluationApp.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace EvaluationApp.Web.Controllers
{
    public class EvaluationController : Controller
    {
        private readonly WebsiteUrlService _websiteUrlService;
        private readonly UrlResponseStatService _urlResponseStatService;
        private readonly IMapper _mapper;

        public EvaluationController(WebsiteUrlService websiteUrlService, UrlResponseStatService urlResponseStatService, IMapper mapper)
        {
            _websiteUrlService = websiteUrlService;
            _urlResponseStatService = urlResponseStatService;
            _mapper = mapper;
        }

        public ActionResult Index(string site)
        {
            if (String.IsNullOrEmpty(site))
            {
                return View();
            }
            else
            {
                // TODO: implement The Single Responsibility Principle
                WebsiteUrlModel website = new WebsiteUrlModel { Url = site, DateCreated = DateTime.Now };
                int websiteId = _websiteUrlService.Create(_mapper.Map<WebsiteUrlBL>(website));
                string urlString = site + "/sitemap.xml";

                List<UrlResponseStatModel> urls = new List<UrlResponseStatModel>();

                XmlTextReader reader = new XmlTextReader(urlString);
                while (reader.Read())
                {
                    if (reader.NodeType == XmlNodeType.Text)
                    {
                        HttpWebRequest request = (HttpWebRequest)WebRequest.Create(urlString);

                        Stopwatch timer = new Stopwatch();
                        timer.Start();

                        HttpWebResponse response = (HttpWebResponse)request.GetResponse();

                        timer.Stop();

                        TimeSpan timeTaken = timer.Elapsed;

                        UrlResponseStatModel model = new UrlResponseStatModel
                        {
                            Date = DateTime.Now,
                            WebsiteUrlId = websiteId,
                            Url = reader.Value.ToString(),
                            ResponseTimeMs = (int)timeTaken.TotalMilliseconds
                        };
                        urls.Add(model);
                    }
                }
                ViewBag.Sitemap = urls;

                return View("Index", null, site);
            }
        }
    }
}

EvaluationApp.Web/Views/Evaluation/Index.cshtml
@using EvaluationApp.Web.Models
@model string

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<form method="get">
    <label for="site">URL</label>
    <input type="text" name="site" />
    <input type="submit" name="name" value="Create sitemap" />   
</form>

@if (ViewBag.Sitemap != null)
{
    foreach(UrlResponseStatModel url in ViewBag.Sitemap)
    {
        <span>@url.Url</span>
        <span>@url.ResponseTimeMs</span>
        <br />
    }
}

EvaluationApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Url response stats", "Index", "Evaluation")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>